### ISSUE TITLE
[RFC] Account Fiscal Position Rule VAT

### ISSUE THREAD

**Issue by ThomasBinsfeld** [OCA/account-fiscal-rule#101]
We need to handle partners with multiple VAT numbers and use the right one on invoices.

__The idea is:__

 * Using the module `partner_identification` (PR to review: https://github.com/OCA/partner-contact/pull/815) to manage several VAT numbers on the same partner. With a new "VAT" type, the identification line would be related to the tax administration that issued the VAT number. The VAT number would be checked with VIES, according to the same rule as the regular Odoo VAT number.
 * On the fiscal position, a new field would allow to define a tax administration (res.partner)
 * On an invoice which uses a fiscal position with a tax administration on it, we can find the right tax number for the partner and the company. Otherwise, the standard behavior would be preserved.

The module would be on __OCA/account-fiscal-rule__, named __account_fiscal_position_rule_vat__.

**Comment by sbidoul** [comment]
This module is useful in a situation where a single company is subject to VAT in different countries.
This allow setting multiple VAT numbers on any partner and select the right one depending on the fiscal position.

Regarding the name, maybe `account_multi_vat` would be more explicit?
