### ISSUE TITLE
account_avatax: Tax not reset in Customer Invoice

### ISSUE THREAD

**Issue by atchuthan** [OCA/account-fiscal-rule#147]
Steps to reproduce the issue
1. Create sales order and do a down payment with 50% and post the payment.  The tax will be applied in the invoice.
2. As down payment product needs to be set with Product tax code = NT (non-taxable code with service type) and post the Invoice once again.
3. When you check the transaction in Avatax, no taxes will be available in the transaction but the tax is still present in Odoo.

@dreispt Please let me know if you need more info to figure out the cause.

**Comment by dreispt** [comment]
The "post the Invoice once again" is not clear to me, you can only post an invoice once, right?

**Comment by dreispt** [comment]
Also, at step 1, no tax should be applied on the down payment. Make sure it is properly configured.

**Comment by atchuthan** [comment]
No, my point is that we are able to cancel the invoice and the transaction will be voided in Avatax, then we can re-post the invoice in odoo and it will un-void the transaction.

Yes, I agree with the configuration.  But, my point is that we are able to send the Product Tax code in the transaction line and If the customer made some mistake with the configuration and made the correction in the product.  The tax is not reset at the time of the second post

**Comment by dreispt** [comment]
Voiding transactions is implemented.
Re-posting the Invoice should replace the original posted transaction.
So I your scenario should be supported.

Can you set a breakpoint here and check what is going on?
https://github.com/OCA/account-fiscal-rule/blob/13.0/account_avatax/models/account_move.py#L166

**Comment by dreispt** [comment]
Inspecting the code, we could have a bug on line 177: perhaps the transaction is just being commited again, and is not replaced...

**Comment by dreispt** [comment]
Can you try this fix?

Replace line 177 with: `return self._avatax_compute_tax(commit=commit)`
This retries the tax computation and commit, after unvoiding the previous transaction.

Now, when cancelling the Invoice, it should be already uncommited, I'm not sure if this is so.
It would be nice if you could also check this in your tests.

Thanks!

**Comment by dreispt** [comment]
Hello @atchuthan, was there a PR for this fix? Thanks!

**Comment by atchuthan** [comment]
I think the easiest way to resolve this might be to reset the avatax_amount, line.avatax_amt_line and line.tax_ids when we use cancel button instead of changing unvoid and commit

**Comment by atchuthan** [comment]
Please share your idea such that I can do the PR

P.S: Sorry for the late reply
