### ISSUE TITLE
[Question] account_avatax: odoo.sh

### ISSUE THREAD

**Issue by atchuthan** [OCA/account-fiscal-rule#148]
@dreispt 
For one of our customers in odoo.sh, we have set up the production account info in the master branch.  When we do a commit in the staging branch, normally odoo tries to download DB from master to the sandbox/staging branch.  And it seems the production avatax configuration is now available in the staging branch.

Is there any easy approach to automatically disable the configuration?

**Comment by dreispt** [comment]
You can create a test Company in the Avatax service,.
When copying a Production database to a Staging environment, you should change the Avatax company code to the test company.

**Comment by atchuthan** [comment]
Yes, we are making the changes manually each time.  But, is there any easy method to automatically disable/change the credential with code.  Like what odoo automatically disables the schedulers

**Comment by dreispt** [comment]
The proper comparison would be disabling/changing email server credentials.
In the OCA there are the server environment modules for this, but I'm not using them myself:
https://github.com/OCA/server-env

**Comment by atchuthan** [comment]
Okay, thanks for the suggestion.
