### ISSUE TITLE
AVATAX credit notes are not using the correct posting date

### ISSUE THREAD

**Issue by dreispt** [OCA/account-fiscal-rule#157]
AVATAX credit notes are not using the correct posting date in AVALARA.
Credit notes should post with the credit date not the original invoice date. 
This works correctly in the v12 connector but not in the account-fiscal-rule connector in OCA.

**Comment by bodedra** [comment]
Issue in this method: https://github.com/OCA/account-fiscal-rule/blob/13.0/account_avatax/models/account_move.py#L108

It should be improve with move.type, if it's refund, use credit memo date.

**Comment by bodedra** [comment]
cc @atchuthan

**Comment by bodedra** [comment]
Close ref: #159
