### ISSUE TITLE
Avalara is attempting to calculate tax on Vendor Bills

### ISSUE THREAD

**Issue by tr3ysmith** [OCA/account-fiscal-rule#167]
Whenever we write a vendor bill, the avatax api attempts to calculate tax on the vendor bill lines. I understand this should be the case for invoices, but shouldn't that be disabled for vendor bills?

**Comment by ray-odoo** [comment]
Not just attempted but reported to Avalara.    This can be worked around by using a Tax Exempt fiscal position for all Vendors, and making this the default for new Vendor.

**Comment by tr3ysmith** [comment]
Yeah its just a pain and if you actually need to sell something to them, and they're not exempt, then its a problem. Its also a pain because it tries to still run address validation as well.

Case in point. Selling to an employee, not tax exempt. Paying an employee as a vendor for reimbursements, shouldn't be taxed. In this case, fiscal rule won't work. It has to be a manual change.

So for right now, we ended up modifying our avatax module to exclude journal entries, vendor bills, and vendor credit notes. when it does the calculation or address validation, it checks to see if its an invoice or not.

**Comment by ray-odoo** [comment]
Also the Fiscal Position seems to not respect the setting on the Vendor and needs to be manually changed on every Bill. 

Can you share the modification with me ray@odoo.com
