### ISSUE TITLE
Unable to install module "account_avatax" because an external dependency is not met: Python library not installed: Avalara

### ISSUE THREAD

**Issue by whit1588816** [OCA/account-fiscal-rule#203]
I see this error when I build my test server. Do I need to install Avalara Dependency myself?

<img width="1439" alt="Screen Shot 2021-05-21 at 9 52 47 AM" src="https://user-images.githubusercontent.com/72826934/119172122-5bfaa100-ba1a-11eb-8b76-bb37e0ad581d.png">

**Comment by bodedra** [comment]
@whit1588816 

IMO issue in your environment and it skips requirement.txt file to install necessary library. 

Run following command to your environment and it will resolve this issue.

> pip install Avalara

Ref: https://github.com/OCA/account-fiscal-rule/blob/14.0/requirements.txt

https://pypi.org/project/Avalara/

@whit1588816 @OCA/accounting-maintainers we can close this issue.

**Comment by dreispt** [comment]
Thank you @bodedra
