### ISSUE TITLE
CALIFORNIA eWaste Support

### ISSUE THREAD

**Issue by ray-odoo** [OCA/account-fiscal-rule#234]
Am I correct in assuming there is no current support for calculating a fixed screen size based eWaste tax on top of the Sales Tax?

Configuring the correct Taxes in Odoo results in them appearing correctly on the lines of a Sales Order or Invoice but the amount of tax is ignored because the call to Avalara populates the sale.order.line.tax.amount column and that is used instead of the Odoo calculated tax amount.

v13

**Comment by dreispt** [comment]
Hello Ray, you are right.

The strategy used by the  current implementation overrides the Odoo tax computations, replacing them with the Avalara computed amounts.
This strategy is the one used since the inception of the app, by Odoo, and wasn't changed.

We can help you to address your requirement.
Email me at dreis - at - opensourceintegrators.com and we can get a conversation started.

Thank you

**Comment by ray-odoo** [comment]
Thanks Daniel.

Customer has elected to have their development team try first, so I will have them share their work (if it works!) in case it can be useful to you.

**Comment by ray-odoo** [comment]
@dreispt just to update you, the Customer elected to design the change this way:

Instead of the module being responsible for both the % *and* the $$ impact of the tax returned by Avalara, the module will be responsible just for the % and Odoo will be responsible for the $$ impact.

With this change, Odoo correctly calculates the $$ impact of not only the tax returned by Avalara but the fixed eWaste tax added by the User.

They essentially commented out:
1. where the module overwrote the values in price_tax and price_total on sale.order.line
2. where the module overwrote the values in amount_tax and amount_total on sale.order
3. where the module overwrote the values in price_total on account.move.

**Comment by dreispt** [comment]
Thank you for the update Ray.

Mind that Avalara requires connectors to enforce the $$ amounts computed by Avatax (this is one of the certification requirements - see “ Verify Avalara Calculated Tax Amount is used in transaction” at https://developer.avalara.com/certification/avatax/sales-tax-badge/)

So take note that you may have rounding differences between Odoo books and Avatax reports.

A Avalara compliant solution would use the Sales Tax $$ amount, and then add the additional Odoo computed taxes. This is not simple, I wish Odoo tax engine was friendlier for extensions.

--dr
