### ISSUE TITLE
account_fiscal_position_partner_type: suprising behavior on Fiscal Positions

### ISSUE THREAD

**Issue by dreispt** [OCA/account-fiscal-rule#254]
I would expect that a Fiscal Position with empty Fiscal Position Type would apply to any Partner.
I should be able to create a single FP "National Customers", that applies both to B2B and B2C.

Right now this doesn't work.
I need to instead have at least two FPs, duplicates except for the FP Type field: one for B2C and another for B2C.

I would like to change this, and allow an FP with no FP Type set to be applicable to Partners with any FP Type assigned to the,

Thoughts? @pedrobaeza @HaraldPanten @ValentinVinagre

**Comment by pedrobaeza** [comment]
If I don't remember bad, not filling the type on the fiscal position means to not check the type of the partner, so that sounds exactly what you want to achieve. You haven't indicated the Odoo version though.

**Comment by ValentinVinagre** [comment]
Hi @dreispt , if you leave the field empty in the partner, the search will ignore this new field when searching for the tax position. Have you tried it with this configuration?

**Comment by dreispt** [comment]
@ValentinVinagre Yes, that is true, but it is not a solution.
I want for a FP to apply to B2C only, B2B only, or to any of these.
Following Pedro's feedback, I'll propose an implementation for this.
