### ISSUE TITLE
[14.0][15.0] account_avatax: updating Enterprise code breaks the Avatax connector!

### ISSUE THREAD

**Issue by dreispt** [OCA/account-fiscal-rule#283]
Odoo SA rolled out their own `account_avatax` and `account_avatax_sale` models as EE modules, for 14.0 and 15.0.
This hijacks the OCA module names, and breaks current installations.

**If you are using OCA Avatax modules, don't update your Odoo Enterprise code!**

Upstream discussion:
https://github.com/odoo/enterprise/pull/23535

**Comment by atchuthan** [comment]
:+1:

**Comment by HviorForgeFlow** [comment]
What about rename modules to oca_account_avatax*? @dreispt

**Comment by dreispt** [comment]
@HviorForgeFlow That migh b ethe way to go.
Should we add "oca" as a prefix or as a suffix (`account_avatax*oca`)?
Are you aware of similar cases?

**Comment by HviorForgeFlow** [comment]
First I saw it had been added as a suffix. It doesn't matters anyway.
https://github.com/OCA/manufacture/tree/14.0/quality_control_oca

**Comment by dreispt** [comment]
Implemented:
- v14 #320 
- v15 #314
