### ISSUE TITLE
Colorado’s new retail delivery fee takes effect July 1, 2022

### ISSUE THREAD

**Issue by atchuthan** [OCA/account-fiscal-rule#293]
https://www.avalara.com/blog/en/north-america/2022/05/colorados-new-retail-delivery-fee-takes-effect-july-1-2022.html
https://tax.colorado.gov/retail-delivery-fee

@dreispt Is there any plan to add this in Avatax module? Or any other plans?

If no plan is prepared, then we plan to add this as an option in avatax configuration

`Merchants subject to this fee will need to add a $0 line item to their orders with the OF400000 tax code.`
> New order line will be created similar to adding shipping line(with product taxcode=OF400000) and this info will be obtained from avatax config i.e. it will have the Fed. State and the amount such that we can do this for any other Fed. State in future.  We will currently have Fed. State = CO and Amount=$0.27

**Comment by dreispt** [comment]
Hello, this hasn’t been requested by our customers yet, so no immediate plans.
Feel free to go ahead.

Thanks
Daniel

**Comment by dnplkndll** [comment]
@atchuthan would all CO deliveries be able to have the line sent? The fee only applies on shipped good on taxable sales. But you do not know the taxable state until the request come back. We have added the code to the ecom systems. but then will manually apply the line using an approval rule pending the configuration.  I saw there was talk about returning the fees separate from the taxes as it is some type on environmental fee versus a sale tax. So would you want to split that component so as not to aggregate into the rate and then would not match the %? Wondering if this is a new wave of fees on the economic nexus state coming and will need to apply on all delivery type orders. In which case is there a standard way to know the Sale Order was shipped versus CustomerPickUp ?

CC: @enterlineconnor @wlin-kencove

**Comment by atchuthan** [comment]
Added PR https://github.com/OCA/account-fiscal-rule/pull/294
