### ISSUE TITLE
14.0 account_product_fiscal_classification : Traceability on changes

### ISSUE THREAD

**Issue by bealdav** [OCA/account-fiscal-rule#344]
**Describe the solution you'd like**
Because this module have a big impact on products and accounting
I would like add chatter info to `account.product.fiscal.classification` 
i.e. get info about updated tax m2m on this object, and name field
For m2m it would required to use `message_post` in `write` to get info about changes

**Describe alternatives you've considered**
Pray that anybody try things ! No always proof 

cc @legalsylvain @florian-dacosta @sebastienbeau

**Comment by legalsylvain** [comment]
Hi. the track_visibility is enabled on product, [thanks to you](https://github.com/OCA/account-fiscal-rule/commit/463bb824941759c2472233c0ee80b16efbdd5115) ! (And yes, it's important).

What about to make the same, regarding the fields sale_tax_ids and purchase_tax_ids (and name) ? 

(and adding inheritance in the module account.product.fiscal.classification to have the chatter enabled ?)

**Comment by bealdav** [comment]
Hi  @legalsylvain 
For m2m fields I plan to override `write()` and call `message_post()` inside to define old and new values

Ok for that ?

**Comment by legalsylvain** [comment]
>  For m2m fields I plan to override write() and call message_post() inside to define old and new values

        track_visibility="onchange" doesn't work for m2m ?

**Comment by legalsylvain** [comment]
Side question : could you review this one ? https://github.com/OCA/account-fiscal-rule/pull/327

**Comment by bealdav** [comment]
Nope

>    track_visibility="onchange" doesn't work for m2m ?

**Comment by legalsylvain** [comment]
>    track_visibility="onchange" doesn't work for m2m ?

[Damn'it !](https://i.giphy.com/media/OPQkiDUE3GSiRQacfa/giphy.webp)

So indeed, we should override write function. Could you make a PR against https://github.com/OCA/account-fiscal-rule/pull/327 ? 

Thanks !

**Comment by bealdav** [comment]
I'll make a PR on 14.0 first and then apply changes on your PR 16.0, isn't it ?

**Comment by legalsylvain** [comment]
> I'll make a PR on 14.0 first and then apply changes on your PR 16.0, isn't it ?

as you wish !
