### ISSUE TITLE
Wrong argument select in fields company_id and fiscal_position_id

### ISSUE THREAD

**Issue by renatonlima** [OCA/account-fiscal-rule#63]
![image](https://cloud.githubusercontent.com/assets/211005/21157727/91e99818-c161-11e6-8b84-27021180fe0c.png)

**Comment by yk2kus** [comment]
in which version? in V10 it shouldn't be the case.
https://goo.gl/MNfRRo
https://goo.gl/EpehHb
both fields use 'index' instead of 'select'

**Comment by renatonlima** [comment]
I will test new branch 10

**Comment by legalsylvain** [comment]
@renatonlima, did you make the fix finally ? 
closing in the meantime. Feel free to reopen.
regards.
