### ISSUE TITLE
[9.0] Odoo on_change conflicts

### ISSUE THREAD

**Issue by Armitxes** [OCA/account-fiscal-rule#65]
I got an issue where the 'onchange_partner_shipping_id' at 'odoo/addons/sale/sale.py' overwrites the changes made by the 'onchange_fiscal_position_map' of the fiscal module.

It doesn't matter if the fiscal position in the partner is set or not. The odoo default behaviour always overwrites the changes made by this modules.

**Comment by pedrobaeza** [comment]
Can you put the reference to the conflicting line that overwrites this?

**Comment by legalsylvain** [comment]
closing, due to inactivity. If the bug persist, please reopen the Issue, adding the conflicting lines.

regards.
