### ISSUE TITLE
[8.0] [Error] account_product_fiscal_classification

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/account-fiscal-rule#76]
When changing a tax on a fiscal classification on a system with multiple `product.template` records sharing that same fiscal classification, [this line of code](https://github.com/OCA/account-fiscal-rule/blob/8.0/account_product_fiscal_classification/models/product_template.py#L86) throws a `ValueError` of "Expected singleton".

**Comment by legalsylvain** [comment]
impacted version 8.0 + 10.0.
bug confirmed.
could you provide a fix ? a simple

```for template in self:```

should fix the problem.

**Comment by thomaspaulb** [comment]
@legalsylvain Instead of the `for template in self:` I had chosen to get the `id` from `vals` instead of from `self`, I think it could also fix the problem, what do you think
