### ISSUE TITLE
[RFC] account_product_fiscal_classification road map

### ISSUE THREAD

**Issue by legalsylvain** [OCA/account-fiscal-rule#91]
Hi all, 
I just write here some points to take into account, when migrating the module ``account_product_fiscal_classification`` in more recent version : 

- IMP : include the code of ``account_product_fiscal_classification_usage_group`` into this module. (see #84 and current 8.0 module : https://github.com/grap/grap-odoo-incubator/tree/8.0/account_product_fiscal_classification_usage_group)
- FIX : for the time being, ``account.product.fiscal.classification.template`` have no link to the account chart template. it should be added to make it consistent in a multi localization env. (as for ``account.tax.template``, and other template).

CC : @renatonlima, @rvalyi, @quentinDupont 

regards. 

Feel free to add more comments.

**Comment by PierrickBrun** [comment]
I will migrate this module soon, thank you for the inputs

@bealdav

**Comment by PierrickBrun** [comment]
Here is my PR #92

**Comment by bealdav** [comment]
Thanks a lot @PierrickBrun 

Please as said previously we must split the module in 2 parts to put tests in _example to avoid dependency on l10n_coa.

Thanks
